spring.datasource.url=jdbc:sqlserver://;serverName=localhost;databaseName=BookHub;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


jwt.secret=tyjrtsrt82378378378378yuiltilyilfyliylgiuliu4523782378378tkyuk
jwt.expiration=900000